apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mohesh-eks-cluster
  region: ap-southeast-1

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 4
  iam:
    withAddonPolicies:
      albIngress: true
